In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import BernoulliNB
param_grid={'alpha':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0], 'force_alpha':[True,False], 'binarize': [0.0], 'fit_prior':[True,False], 'class_prior':[None]}
grid= GridSearchCV(BernoulliNB(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted' )
grid.fit(X_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\Anaconda3run\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,
                                   1.0],
                         'binarize': [0.0], 'class_prior': [None],
                         'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='f1_weighted', verbose=3)

In [12]:
y_pred=grid.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[51,  0],
       [ 3, 79]], dtype=int64)

In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133



In [16]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
roc_score

1.0

In [17]:
print ( " the best parameter is ", grid.best_params_)

 the best parameter is  {'alpha': 0.3, 'binarize': 0.0, 'class_prior': None, 'fit_prior': True, 'force_alpha': True}


In [18]:
grid.cv_results_

{'mean_fit_time': array([0.01994519, 0.00917506, 0.00498228, 0.00738015, 0.00817385,
        0.00598469, 0.00478683, 0.00638037, 0.00678248, 0.00678043,
        0.00578508, 0.00558996, 0.00518603, 0.00518579, 0.00597572,
        0.00618396, 0.00598769, 0.00478907, 0.00538559, 0.00478697,
        0.00518637, 0.00618386, 0.00678182, 0.00678167, 0.00618401,
        0.00578451, 0.00618272, 0.00617647, 0.0085773 , 0.00498672,
        0.00598392, 0.00698137, 0.00478916, 0.00718141, 0.00558476,
        0.0065834 , 0.00737872, 0.00877481, 0.00598259, 0.00578318]),
 'std_fit_time': array([0.00751953, 0.00330304, 0.00062526, 0.00149241, 0.00439075,
        0.00260071, 0.00074632, 0.00174179, 0.00193479, 0.00212876,
        0.00116325, 0.00173709, 0.00097603, 0.00146547, 0.00125753,
        0.0009833 , 0.00260114, 0.00039527, 0.00048797, 0.00074623,
        0.00116257, 0.00247508, 0.00270577, 0.00222003, 0.00171597,
        0.002223  , 0.00193359, 0.00193694, 0.00337353, 0.0006309 ,
        0.002

In [19]:
re=grid.cv_results_

In [20]:
table= pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0        0.019945      0.007520         0.012367        0.001195         0.1   
1        0.009175      0.003303         0.012766        0.001466         0.1   
2        0.004982      0.000625         0.012367        0.002410         0.1   
3        0.007380      0.001492         0.012965        0.001410         0.1   
4        0.008174      0.004391         0.011171        0.000977         0.2   
5        0.005985      0.002601         0.012567        0.004259         0.2   
6        0.004787      0.000746         0.011173        0.000750         0.2   
7        0.006380      0.001742         0.010971        0.000632         0.2   
8        0.006782      0.001935         0.011171        0.000978         0.3   
9        0.006780      0.002129         0.011370        0.001492         0.3   
10       0.005785      0.001163         0.010571        0.000798         0.3   
11       0.005590      0.001737         0.012163        0.002133         0.3   
12       0.005186      0.000976         0.011370        0.001018         0.4   
13       0.005186      0.001465         0.010970        0.000892         0.4   
14       0.005976      0.001258         0.011769        0.001465         0.4   
15       0.006184      0.000983         0.011172        0.000749         0.4   
16       0.005988      0.002601         0.011770        0.001165         0.5   
17       0.004789      0.000395         0.011766        0.001463         0.5   
18       0.005386      0.000488         0.010971        0.000631         0.5   
19       0.004787      0.000746         0.010572        0.000798         0.5   
20       0.005186      0.001163         0.011370        0.000797         0.6   
21       0.006184      0.002475         0.010372        0.000488         0.6   
22       0.006782      0.002706         0.010572        0.000489         0.6   
23       0.006782      0.002220         0.010971        0.001544         0.6   
24       0.006184      0.001716         0.011369        0.001017         0.7   
25       0.005785      0.002223         0.010373        0.000487         0.7   
26       0.006183      0.001934         0.011571        0.001197         0.7   
27       0.006176      0.001937         0.010174        0.000399         0.7   
28       0.008577      0.003374         0.010973        0.001093         0.8   
29       0.004987      0.000631         0.010771        0.000746         0.8   
30       0.005984      0.002524         0.010175        0.000398         0.8   
31       0.006981      0.002443         0.010572        0.000488         0.8   
32       0.004789      0.000400         0.010965        0.000897         0.9   
33       0.007181      0.002475         0.011371        0.001019         0.9   
34       0.005585      0.000489         0.011768        0.001323         0.9   
35       0.006583      0.001622         0.010970        0.001547         0.9   
36       0.007379      0.001852         0.011168        0.001935         1.0   
37       0.008775      0.003854         0.010771        0.000977         1.0   
38       0.005983      0.001260         0.010971        0.000631         1.0   
39       0.005783      0.001163         0.012571        0.003371         1.0   

   param_binarize param_class_prior param_fit_prior param_force_alpha  \
0             0.0              None            True              True   
1             0.0              None            True             False   
2             0.0              None           False              True   
3             0.0              None           False             False   
4             0.0              None            True              True   
5             0.0              None            True             False   
6             0.0              None           False              True   
7             0.0              None           False             False   
8             0.0              None            True              T

In [21]:
grid.best_score_

0.9924868136925202

In [22]:
pre_input= sc.transform([[50,92,10,5,120,60,1.5,143,4,12,61,8000,5,0,0,0,0,1,1,0,1,1,1,0,0,0,0]])
pre_input

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.25720128e-01,  1.18386687e+00,  7.43679000e+00,
         4.68015545e+00, -3.88079651e-01, -2.48869935e-03,
        -2.86774811e-01,  5.15346177e-01, -2.58764074e-01,
        -1.75196181e-01,  2.70805503e+00, -1.31927538e-01,
         3.97885360e-01, -4.92940822e-01, -5.45491499e-01,
        -4.51242628e-01, -1.38409133e-01,  3.89249472e-01,
         5.10552159e-01, -3.42997170e-01,  4.24264069e+00,
         1.35269628e+00,  1.35269628e+00, -2.92770022e-01,
        -1.93649167e+00, -5.22232968e-01, -4.45194562e-01]])

In [23]:
result= grid.predict(pre_input)
result

array([1])