In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [8]:
print(indep.iloc[0])

age               2.000000
bp               76.459948
al                3.000000
su                0.000000
bgr             148.112676
bu               57.482105
sc                3.077356
sod             137.528754
pot               4.627244
hrmo             12.518156
pcv              38.868902
wc             8408.191126
rc                4.705597
sg_b              0.000000
sg_c              1.000000
sg_d              0.000000
sg_e              0.000000
rbc_normal        1.000000
pc_normal         0.000000
pcc_present       0.000000
ba_present        0.000000
htn_yes           0.000000
dm_yes            0.000000
cad_yes           0.000000
appet_yes         1.000000
pe_yes            1.000000
ane_yes           0.000000
Name: 0, dtype: float64


In [9]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [10]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV
param_grid={'alpha':[1,11], 'force_alpha':[True,False], 'fit_prior':[True,False]}
grid= GridSearchCV(CategoricalNB(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted')
grid.fit(indep,dep)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan]
  warnings.warn(
C:\Anaconda3run\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [1, 11], 'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='f1_weighted', verbose=3)

In [11]:
y_pred=grid.predict(indep)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [12]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dep,y_pred)
cm

array([[150,   0],
       [  1, 248]], dtype=int64)

In [13]:
from sklearn.metrics import classification_report
clf_report=classification_report(dep,y_pred)

In [14]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399



In [15]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(dep,grid.predict_proba(indep)[:,1])
roc_score

0.9999196787148594

In [16]:
print ( " the best parameter is ", grid.best_params_)

 the best parameter is  {'alpha': 1, 'fit_prior': True, 'force_alpha': True}


In [17]:
grid.cv_results_

{'mean_fit_time': array([0.02074456, 0.01715298, 0.01575193, 0.01835289, 0.01735349,
        0.01894851, 0.01675496, 0.01615648]),
 'std_fit_time': array([0.00171643, 0.00263121, 0.00170556, 0.00205261, 0.00299917,
        0.00388852, 0.00132383, 0.00146646]),
 'mean_score_time': array([0.01216965, 0.00758343, 0.01356277, 0.00677996, 0.00857716,
        0.00797896, 0.00817838, 0.00658507]),
 'std_score_time': array([0.00460872, 0.00376724, 0.00852453, 0.00277959, 0.00386797,
        0.00302438, 0.0046526 , 0.00386655]),
 'param_alpha': masked_array(data=[1, 1, 1, 1, 11, 11, 11, 11],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_fit_prior': masked_array(data=[True, True, False, False, True, True, False, False],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_force_alpha': masked_array(data=[True, False, True, 

In [18]:
re=grid.cv_results_

In [19]:
table= pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.020745      0.001716         0.012170        0.004609           1   
1       0.017153      0.002631         0.007583        0.003767           1   
2       0.015752      0.001706         0.013563        0.008525           1   
3       0.018353      0.002053         0.006780        0.002780           1   
4       0.017353      0.002999         0.008577        0.003868          11   
5       0.018949      0.003889         0.007979        0.003024          11   
6       0.016755      0.001324         0.008178        0.004653          11   
7       0.016156      0.001466         0.006585        0.003867          11   

  param_fit_prior param_force_alpha  \
0            True              True   
1            True             False   
2           False              True   
3           False             False   
4            True              True   
5            True             False   
6           False              True   
7           False             False   

                                              params  split0_test_score  \
0  {'alpha': 1, 'fit_prior': True, 'force_alpha':...           0.950296   
1  {'alpha': 1, 'fit_prior': True, 'force_alpha':...           0.950296   
2  {'alpha': 1, 'fit_prior': False, 'force_alpha'...           0.950296   
3  {'alpha': 1, 'fit_prior': False, 'force_alpha'...           0.950296   
4  {'alpha': 11, 'fit_prior': True, 'force_alpha'...           0.938022   
5  {'alpha': 11, 'fit_prior': True, 'force_alpha'...           0.938022   
6  {'alpha': 11, 'fit_prior': False, 'force_alpha...           0.938022   
7  {'alpha': 11, 'fit_prior': False, 'force_alpha...           0.938022   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                NaN                NaN                NaN                NaN   
1                NaN                NaN                NaN                NaN   
2                NaN                NaN                NaN                NaN   
3                NaN                NaN                NaN                NaN   
4                NaN                NaN                NaN                NaN   
5                NaN                NaN                NaN                NaN   
6                NaN                NaN                NaN                NaN   
7                NaN                NaN                NaN                NaN   

   mean_test_score  std_test_score  rank_test_score  
0              NaN             NaN                1  
1              NaN             NaN                1  
2              NaN             NaN                1  
3              NaN             NaN                1  
4              NaN             NaN                1  
5              NaN             NaN                1  
6              NaN             NaN                1  
7              NaN             NaN                1

In [20]:
grid.best_score_

nan

In [21]:
pre_input= ([[50,92,5,5,120,60,1.5,143,4,12,54,8000,5,0,0,0,0,1,1,0,1,1,1,0,0,0,0]])

In [22]:
result= grid.predict(pre_input)
result

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([1])