In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid={'weights':["uniform", "distance", None], 'algorithm': ["auto", "ball_tree","kd_tree","brute"], 'leaf_size': [10,20,30], 'p': [1,2,3,4,5]}
grid= GridSearchCV(KNeighborsClassifier(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted' )
grid.fit(X_train,y_train)

Fitting 5 folds for each of 180 candidates, totalling 900 fits


C:\Anaconda3run\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 20, 30], 'p': [1, 2, 3, 4, 5],
                         'weights': ['uniform', 'distance', None]},
             scoring='f1_weighted', verbose=3)

In [12]:
y_pred=grid.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[51,  0],
       [ 9, 73]], dtype=int64)

In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.85      1.00      0.92        51
           1       1.00      0.89      0.94        82

    accuracy                           0.93       133
   macro avg       0.93      0.95      0.93       133
weighted avg       0.94      0.93      0.93       133



In [16]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
roc_score

1.0

In [17]:
print ( " the best parameter is ", grid.best_params_)

 the best parameter is  {'algorithm': 'auto', 'leaf_size': 10, 'p': 3, 'weights': 'distance'}


In [18]:
grid.cv_results_

{'mean_fit_time': array([0.0191494 , 0.00578303, 0.0039896 , 0.00558391, 0.00558438,
        0.00738616, 0.00538149, 0.01037149, 0.00677872, 0.00977306,
        0.0115685 , 0.0037868 , 0.01097007, 0.00698099, 0.01356487,
        0.01077104, 0.00638456, 0.01037183, 0.00558558, 0.00877624,
        0.0041882 , 0.00558629, 0.00777941, 0.01116948, 0.00677919,
        0.01236281, 0.01296439, 0.00737958, 0.00458655, 0.00917444,
        0.00618029, 0.00578403, 0.0081778 , 0.00678177, 0.01037254,
        0.00378995, 0.00778351, 0.00598412, 0.00738068, 0.01236525,
        0.01176829, 0.01495895, 0.01216993, 0.00778112, 0.00658135,
        0.00997419, 0.00698142, 0.01097021, 0.00358572, 0.00558519,
        0.00618124, 0.00678191, 0.01236625, 0.00558481, 0.00877628,
        0.00797791, 0.00857568, 0.00678277, 0.00737853, 0.00717964,
        0.00538554, 0.00498877, 0.00518632, 0.00617995, 0.00618181,
        0.0057838 , 0.00757771, 0.00877523, 0.00538802, 0.00618262,
        0.00897551, 0.00638046,

In [19]:
re=grid.cv_results_

In [20]:
table= pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.019149      0.012979         0.169546        0.032472   
1         0.005783      0.001163         0.103326        0.007582   
2         0.003990      0.000632         0.105718        0.001669   
3         0.005584      0.001850         0.098937        0.003362   
4         0.005584      0.002862         0.100929        0.002849   
..             ...           ...              ...             ...   
175       0.008177      0.009386         0.104521        0.016321   
176       0.009570      0.007768         0.114692        0.010364   
177       0.006978      0.007054         0.128059        0.006814   
178       0.012767      0.010235         0.115889        0.020551   
179       0.006982      0.006020         0.113695        0.007384   

    param_algorithm param_leaf_size param_p param_weights  \
0              auto              10       1       uniform   
1              auto              10       1      distance   
2              auto              10       1          None   
3              auto              10       2       uniform   
4              auto              10       2      distance   
..              ...             ...     ...           ...   
175           brute              30       4      distance   
176           brute              30       4          None   
177           brute              30       5       uniform   
178           brute              30       5      distance   
179           brute              30       5          None   

                                                params  split0_test_score  \
0    {'algorithm': 'auto', 'leaf_size': 10, 'p': 1,...           0.926978   
1    {'algorithm': 'auto', 'leaf_size': 10, 'p': 1,...           0.926978   
2    {'algorithm': 'auto', 'leaf_size': 10, 'p': 1,...           0.926978   
3    {'algorithm': 'auto', 'leaf_size': 10, 'p': 2,...           0.963284   
4    {'algorithm': 'auto', 'leaf_size': 10, 'p': 2,...           0.963284   
..                                                 ...                ...   
175  {'algorithm': 'brute', 'leaf_size': 30, 'p': 4...           0.963284   
176  {'algorithm': 'brute', 'leaf_size': 30, 'p': 4...           0.963284   
177  {'algorithm': 'brute', 'leaf_size': 30, 'p': 5...           0.963284   
178  {'algorithm': 'brute', 'leaf_size': 30, 'p': 5...           0.963284   
179  {'algorithm': 'brute', 'leaf_size': 30, 'p': 5...           0.963284   

     split1_test_score  split2_test_score  split3_test_score  \
0             0.981233           0.944023           0.981217   
1             0.981233           0.944023           0.981217   
2             0.981233           0.944023           0.981217   
3             0.962636           0.944023           0.962573   
4             0.981233           0.944023           0.962573   
..                 ...                ...                ...   
175           0.943699           0.944023           0.981217   
176           0.925272           0.944023           0.981217   
177           0.925272           0.944023           0.981217   
178           0.943699           0.944023           0.981217   
179           0.925272           0.944023           0.981217   

     split4_test_score  mean_test_score  std_test_score  rank_test_score  
0             0.981217         0.962934        0.023038               37  
1             0.981217         0.962934        0.023038               37  
2             0.981217         0.962934        0.023038               37  
3             0.962573         0.959018        0.007502              109  
4             0.962573         0.962737        0.011770               73  
..                 ...              ...             ...              ...  
175           0.981217         0.962688        0.016709               85  
176           0.981217         0.959002        0.021760              133  
177           0.981217         0.959002        0.021760              133  

In [21]:
grid.best_score_

0.9701947865415057

In [23]:
pre_input= sc.transform([[50,92,10,5,120,60,1.5,143,4,12,61,8000,5,0,0,0,0,1,1,0,1,1,1,0,0,0,0]])
pre_input

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.25720128e-01,  1.18386687e+00,  7.43679000e+00,
         4.68015545e+00, -3.88079651e-01, -2.48869935e-03,
        -2.86774811e-01,  5.15346177e-01, -2.58764074e-01,
        -1.75196181e-01,  2.70805503e+00, -1.31927538e-01,
         3.97885360e-01, -4.92940822e-01, -5.45491499e-01,
        -4.51242628e-01, -1.38409133e-01,  3.89249472e-01,
         5.10552159e-01, -3.42997170e-01,  4.24264069e+00,
         1.35269628e+00,  1.35269628e+00, -2.92770022e-01,
        -1.93649167e+00, -5.22232968e-01, -4.45194562e-01]])

In [24]:
result= grid.predict(pre_input)
result

array([1])