In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
param_grid= { 'penalty': ['l1', 'l2', 'elasticnet', None] , 'class_weight': ['balanced', 'dict', None], 'solver':['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'], 'C':[1,10,20,100]}
grid= GridSearchCV(LogisticRegression(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted' )
grid.fit(X_train,y_train)

Fitting 5 folds for each of 288 candidates, totalling 1440 fits


C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
920 fits failed out of a total of 1440.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3run\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1168, in fit
    solver = _check_solver(self.solver, self.pe

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [1, 10, 20, 100],
                         'class_weight': ['balanced', 'dict', None],
                         'penalty': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='f1_weighted', verbose=3)

In [12]:
y_pred=grid.predict(X_test) 
y_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[51  0]
 [ 2 80]]


In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        51
           1       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133



In [16]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
roc_score

1.0

In [17]:
grid.best_params_

{'C': 1, 'class_weight': 'balanced', 'penalty': 'l2', 'solver': 'lbfgs'}

In [18]:
print("The best parameters are:", grid.best_params_)

The best parameters are: {'C': 1, 'class_weight': 'balanced', 'penalty': 'l2', 'solver': 'lbfgs'}


In [19]:
re=grid.cv_results_

In [20]:
grid.best_score_

0.9888038639876322

In [21]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0         0.001196      0.000399         0.000000        0.000000       1   
1         0.008977      0.002186         0.012770        0.001720       1   
2         0.001595      0.000491         0.000000        0.000000       1   
3         0.001197      0.000399         0.000000        0.000000       1   
4         0.001000      0.000005         0.000000        0.000000       1   
..             ...           ...              ...             ...     ...   
283       0.005785      0.001934         0.000000        0.000000     100   
284       0.015960      0.001410         0.009172        0.002127     100   
285       0.011170      0.000978         0.011769        0.000978     100   
286       0.019945      0.004036         0.010572        0.001497     100   
287       0.021742      0.005761         0.013365        0.006295     100   

    param_class_weight param_penalty     param_solver  \
0             balanced            l1            lbfgs   
1             balanced            l1        liblinear   
2             balanced            l1        newton-cg   
3             balanced            l1  newton-cholesky   
4             balanced            l1              sag   
..                 ...           ...              ...   
283               None          None        liblinear   
284               None          None        newton-cg   
285               None          None  newton-cholesky   
286               None          None              sag   
287               None          None             saga   

                                                params  split0_test_score  \
0    {'C': 1, 'class_weight': 'balanced', 'penalty'...                NaN   
1    {'C': 1, 'class_weight': 'balanced', 'penalty'...           0.981569   
2    {'C': 1, 'class_weight': 'balanced', 'penalty'...                NaN   
3    {'C': 1, 'class_weight': 'balanced', 'penalty'...                NaN   
4    {'C': 1, 'class_weight': 'balanced', 'penalty'...                NaN   
..                                                 ...                ...   
283  {'C': 100, 'class_weight': None, 'penalty': No...                NaN   
284  {'C': 100, 'class_weight': None, 'penalty': No...           0.945100   
285  {'C': 100, 'class_weight': None, 'penalty': No...           0.963284   
286  {'C': 100, 'class_weight': None, 'penalty': No...           0.963284   
287  {'C': 100, 'class_weight': None, 'penalty': No...           0.963284   

     split1_test_score  split2_test_score  split3_test_score  \
0                  NaN                NaN                NaN   
1             0.981233           0.962573           0.962573   
2                  NaN                NaN                NaN   
3                  NaN                NaN                NaN   
4                  NaN                NaN                NaN   
..                 ...                ...                ...   
283                NaN                NaN                NaN   
284           0.962636           0.925524           0.981217   
285           0.981233           0.925524           0.962573   
286           0.981233           0.981217           0.981217   
287           0.981233           0.981217           0.981217   

     split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                  NaN              NaN             NaN              105  
1             0.962573         0.970104        0.009224               76  
2                  NaN              NaN             NaN              105  
3                  NaN              NaN             NaN              105  
4                  NaN              NaN             NaN              105  
..                 ...              ...             ...              ...  
283                NaN              NaN             NaN              105  
284           0.981217         0.959139        0.021513               93  
285           0.962573    

In [23]:
pre_input= sc.transform([[50,92,10,5,120,60,1.5,143,4,12,61,8000,5,0,0,0,0,1,1,0,1,1,1,0,0,0,0]])
pre_input

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.25720128e-01,  1.18386687e+00,  7.43679000e+00,
         4.68015545e+00, -3.88079651e-01, -2.48869935e-03,
        -2.86774811e-01,  5.15346177e-01, -2.58764074e-01,
        -1.75196181e-01,  2.70805503e+00, -1.31927538e-01,
         3.97885360e-01, -4.92940822e-01, -5.45491499e-01,
        -4.51242628e-01, -1.38409133e-01,  3.89249472e-01,
         5.10552159e-01, -3.42997170e-01,  4.24264069e+00,
         1.35269628e+00,  1.35269628e+00, -2.92770022e-01,
        -1.93649167e+00, -5.22232968e-01, -4.45194562e-01]])

In [24]:
result= grid.predict(pre_input)
result

array([1])