In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [11]:
import pickle
filename="std_dataset_RF.pkl"
pickle.dump(sc,open("std_dataset_RF.pkl",'wb'))

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid={'criterion':["gini", "entropy", "log_loss"], 'class_weight': ['balanced', 'dict', None], 'max_features': [None,"sqrt", "log2"], 'n_estimators':[10,50,100], "random_state":[None]}
grid= GridSearchCV(RandomForestClassifier(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted' )
grid.fit(X_train,y_train)

Fitting 5 folds for each of 81 candidates, totalling 405 fits


C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
135 fits failed out of a total of 405.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
135 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3run\Lib\site-packages\sklearn\utils\_param_validation.py", line 

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'dict', None],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100],
                         'random_state': [None]},
             scoring='f1_weighted', verbose=3)

In [13]:
y_pred=grid.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[51,  0],
       [ 0, 82]], dtype=int64)

In [15]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        51
           1       1.00      1.00      1.00        82

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133



In [17]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
roc_score

0.9999999999999999

In [18]:
print ( " the best parameter is ", grid.best_params_)

 the best parameter is  {'class_weight': 'balanced', 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100, 'random_state': None}


In [19]:
grid.cv_results_

{'mean_fit_time': array([0.05206017, 0.1811131 , 0.35784383, 0.03391318, 0.13483944,
        0.26229877, 0.03471155, 0.13264403, 0.27406673, 0.04348135,
        0.18670025, 0.35225482, 0.0357017 , 0.14281492, 0.25611482,
        0.03330526, 0.13762884, 0.26728492, 0.04069109, 0.18410692,
        0.35923948, 0.03589911, 0.1482028 , 0.2577105 , 0.03510528,
        0.13284397, 0.27406797, 0.00079732, 0.00080042, 0.00100079,
        0.00099792, 0.00100069, 0.00099669, 0.00099735, 0.00119944,
        0.00119667, 0.00140147, 0.00099549, 0.00079741, 0.0007977 ,
        0.00059886, 0.00039921, 0.00159545, 0.0007957 , 0.00059662,
        0.00079789, 0.00099545, 0.00079517, 0.00079837, 0.00099649,
        0.00039864, 0.00099168, 0.00099816, 0.00120378, 0.0414844 ,
        0.1797173 , 0.36123486, 0.03750038, 0.12924995, 0.25711284,
        0.02932286, 0.13124652, 0.25730996, 0.04188795, 0.18151822,
        0.35006227, 0.03091712, 0.12825541, 0.26070151, 0.03151603,
        0.13105426, 0.26230536,

In [20]:
re=grid.cv_results_

In [21]:
table= pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.052060      0.007092         0.014162        0.001162   
1        0.181113      0.013524         0.017753        0.000978   
2        0.357844      0.010120         0.028125        0.003478   
3        0.033913      0.007053         0.013562        0.000798   
4        0.134839      0.006776         0.020346        0.002862   
..            ...           ...              ...             ...   
76       0.129453      0.009922         0.019747        0.002779   
77       0.262094      0.004519         0.025733        0.001828   
78       0.035704      0.009942         0.013566        0.003312   
79       0.129855      0.007065         0.018149        0.000743   
80       0.253119      0.011975         0.035706        0.019126   

   param_class_weight param_criterion param_max_features param_n_estimators  \
0            balanced            gini               None                 10   
1            balanced            gini               None                 50   
2            balanced            gini               None                100   
3            balanced            gini               sqrt                 10   
4            balanced            gini               sqrt                 50   
..                ...             ...                ...                ...   
76               None        log_loss               sqrt                 50   
77               None        log_loss               sqrt                100   
78               None        log_loss               log2                 10   
79               None        log_loss               log2                 50   
80               None        log_loss               log2                100   

   param_random_state                                             params  \
0                None  {'class_weight': 'balanced', 'criterion': 'gin...   
1                None  {'class_weight': 'balanced', 'criterion': 'gin...   
2                None  {'class_weight': 'balanced', 'criterion': 'gin...   
3                None  {'class_weight': 'balanced', 'criterion': 'gin...   
4                None  {'class_weight': 'balanced', 'criterion': 'gin...   
..                ...                                                ...   
76               None  {'class_weight': None, 'criterion': 'log_loss'...   
77               None  {'class_weight': None, 'criterion': 'log_loss'...   
78               None  {'class_weight': None, 'criterion': 'log_loss'...   
79               None  {'class_weight': None, 'criterion': 'log_loss'...   
80               None  {'class_weight': None, 'criterion': 'log_loss'...   

    split0_test_score  split1_test_score  split2_test_score  \
0            0.963284           0.942166           0.907035   
1            0.962963           0.942166           0.962573   
2            0.944707           0.942166           0.944023   
3            0.963284           0.981014           0.944023   
4            0.981569           0.981014           0.944023   
..                ...                ...                ...   
76           0.981569           0.981014           0.981217   
77           1.000000           0.961755           0.981217   
78           0.981569           0.981014           0.944023   
79           1.000000           0.961755           0.944023   
80           1.000000           0.942166           0.981217   

    split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0            0.942332           0.981031         0.947170        0.024761   
1            0.903887           0.981031         0.950524        0.026365   
2            0.922492           0.981031         0.946884        0.018954   
3            0.962264           1.000000         0.970117        0.018979   
4            0.981031           0.981031         0.973734        0.014857   
..                ...                ...              ...             ...   
76           0.981031        

In [22]:
grid.best_score_

0.9886523692502024

In [23]:
pre_input= sc.transform([[50,92,10,5,120,60,1.5,143,4,12,61,8000,5,0,0,0,0,1,1,0,1,1,1,0,0,0,0]])
pre_input

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.25720128e-01,  1.18386687e+00,  7.43679000e+00,
         4.68015545e+00, -3.88079651e-01, -2.48869935e-03,
        -2.86774811e-01,  5.15346177e-01, -2.58764074e-01,
        -1.75196181e-01,  2.70805503e+00, -1.31927538e-01,
         3.97885360e-01, -4.92940822e-01, -5.45491499e-01,
        -4.51242628e-01, -1.38409133e-01,  3.89249472e-01,
         5.10552159e-01, -3.42997170e-01,  4.24264069e+00,
         1.35269628e+00,  1.35269628e+00, -2.92770022e-01,
        -1.93649167e+00, -5.22232968e-01, -4.45194562e-01]])

In [24]:
result= grid.predict(pre_input)
result

array([1])

In [25]:
import pickle
filename="final_modelCKD_RF.sav"
pickle.dump(grid,open("final_modelCKD_RF.sav",'wb'))

In [26]:
final_model=pickle.load(open("final_modelCKD_RF.sav",'rb'))
result= final_model.predict(pre_input)
result

array([1])