In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=dataset[["Gender_Male","Age",'EstimatedSalary']]
dep=dataset[["Purchased"]]

In [7]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import BernoulliNB
param_grid={'alpha':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0], 'force_alpha':[True,False], 'binarize': [0.0], 'fit_prior':[True,False], 'class_prior':[None]}
grid= GridSearchCV(BernoulliNB(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted' )
grid.fit(X_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\Anaconda3run\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,
                                   1.0],
                         'binarize': [0.0], 'class_prior': [None],
                         'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='f1_weighted', verbose=3)

In [12]:
y_pred=grid.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[64, 21],
       [ 9, 40]], dtype=int64)

In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.88      0.75      0.81        85
           1       0.66      0.82      0.73        49

    accuracy                           0.78       134
   macro avg       0.77      0.78      0.77       134
weighted avg       0.80      0.78      0.78       134



In [16]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
roc_score

0.8474189675870348

In [17]:
print ( " the best parameter is ", grid.best_params_)

 the best parameter is  {'alpha': 0.1, 'binarize': 0.0, 'class_prior': None, 'fit_prior': False, 'force_alpha': True}


In [18]:
grid.cv_results_

{'mean_fit_time': array([0.0171535 , 0.00797811, 0.00757875, 0.00578442, 0.00498452,
        0.00578632, 0.00558491, 0.00558548, 0.00518217, 0.00458813,
        0.00498686, 0.00578547, 0.00498624, 0.00598483, 0.00758009,
        0.0063839 , 0.00518675, 0.00458813, 0.00498395, 0.00638175,
        0.00877705, 0.00578413, 0.00478668, 0.00558553, 0.00638337,
        0.00658035, 0.00957384, 0.00618286, 0.00618181, 0.00678186,
        0.00518689, 0.00578914, 0.00737734, 0.00677929, 0.00498638,
        0.00478821, 0.0053853 , 0.00418839, 0.00558558, 0.00658302]),
 'std_fit_time': array([5.89644531e-03, 2.09178354e-03, 1.95400895e-03, 3.98708684e-04,
        2.69571190e-06, 1.16359910e-03, 7.96652375e-04, 1.19727471e-03,
        1.93681026e-03, 7.98583933e-04, 1.54501837e-03, 1.71581730e-03,
        6.29923100e-04, 2.27311779e-03, 4.25956449e-03, 1.49175065e-03,
        9.76853604e-04, 7.97510354e-04, 1.09573057e-03, 2.86404007e-03,
        4.65225308e-03, 1.59667143e-03, 7.46595382e-04, 1.737

In [19]:
re=grid.cv_results_

In [20]:
table= pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0        0.017154      0.005896         0.013764    1.162401e-03         0.1   
1        0.007978      0.002092         0.011369    1.017785e-03         0.1   
2        0.007579      0.001954         0.011171    7.463530e-04         0.1   
3        0.005784      0.000399         0.011768    1.595825e-03         0.1   
4        0.004985      0.000003         0.012565    1.019778e-03         0.2   
5        0.005786      0.001164         0.012165    1.719272e-03         0.2   
6        0.005585      0.000797         0.011766    1.160304e-03         0.2   
7        0.005585      0.001197         0.011169    1.163146e-03         0.2   
8        0.005182      0.001937         0.012566    1.847947e-03         0.3   
9        0.004588      0.000799         0.011170    1.163326e-03         0.3   
10       0.004987      0.001545         0.010572    7.984404e-04         0.3   
11       0.005785      0.001716         0.011370    1.492025e-03         0.3   
12       0.004986      0.000630         0.010771    7.461874e-04         0.4   
13       0.005985      0.002273         0.010572    4.874878e-04         0.4   
14       0.007580      0.004260         0.011370    1.352557e-03         0.4   
15       0.006384      0.001492         0.010974    8.878849e-04         0.4   
16       0.005187      0.000977         0.010374    4.872295e-04         0.5   
17       0.004588      0.000798         0.011174    1.159116e-03         0.5   
18       0.004984      0.001096         0.011369    1.492107e-03         0.5   
19       0.006382      0.002864         0.012168    1.716771e-03         0.5   
20       0.008777      0.004652         0.011766    1.160220e-03         0.6   
21       0.005784      0.001597         0.010578    7.935871e-04         0.6   
22       0.004787      0.000747         0.009973    6.217196e-07         0.6   
23       0.005586      0.001738         0.010173    3.992564e-04         0.6   
24       0.006383      0.001850         0.011369    1.196353e-03         0.7   
25       0.006580      0.001951         0.011170    1.465791e-03         0.7   
26       0.009574      0.004575         0.010572    7.980596e-04         0.7   
27       0.006183      0.002034         0.010174    9.778465e-04         0.7   
28       0.006182      0.002474         0.010771    9.763964e-04         0.8   
29       0.006782      0.001935         0.011968    2.091306e-03         0.8   
30       0.005187      0.001164         0.010972    8.929799e-04         0.8   
31       0.005789      0.000756         0.010968    8.838588e-04         0.8   
32       0.007377      0.004911         0.010771    7.453975e-04         0.9   
33       0.006779      0.003182         0.010572    7.982384e-04         0.9   
34       0.004986      0.001093         0.011771    1.326433e-03         0.9   
35       0.004788      0.000746         0.010972    1.089709e-03         0.9   
36       0.005385      0.001353         0.011769    1.323226e-03         1.0   
37       0.004188      0.000399         0.012766    4.107498e-03         1.0   
38       0.005586      0.001353         0.010771    1.162459e-03         1.0   
39       0.006583      0.003254         0.010570    7.989898e-04         1.0   

   param_binarize param_class_prior param_fit_prior param_force_alpha  \
0             0.0              None            True              True   
1             0.0              None            True             False   
2             0.0              None           False              True   
3             0.0              None           False             False   
4             0.0              None            True              True   
5             0.0              None            True             False   
6             0.0              None           False              True   
7             0.0              None           False             False   
8             0.0              None            True              T

In [21]:
grid.best_score_

0.7235473441626866

In [24]:
pre_input= sc.transform([[0,35,60000]])
pre_input

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.99250926, -0.27290378, -0.27655878]])

In [25]:
result= grid.predict(pre_input)
result

array([0], dtype=int64)