In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=dataset[["Gender_Male","Age",'EstimatedSalary']]
dep=dataset[["Purchased"]]

In [7]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid={'criterion':["gini", "entropy", "log_loss"], 'splitter': ["best", "random"], 'class_weight': ['balanced', 'dict', None], 'max_features': [None,"sqrt", "log2"]}
grid= GridSearchCV(DecisionTreeClassifier(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted' )
grid.fit(X_train,y_train)

Fitting 5 folds for each of 54 candidates, totalling 270 fits


C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
90 fits failed out of a total of 270.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
90 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3run\Lib\site-packages\sklearn\utils\_param_validation.py", line 95

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'dict', None],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [11]:
y_pred=grid.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[76,  9],
       [ 8, 41]], dtype=int64)

In [13]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [14]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.90      0.89      0.90        85
           1       0.82      0.84      0.83        49

    accuracy                           0.87       134
   macro avg       0.86      0.87      0.86       134
weighted avg       0.87      0.87      0.87       134



In [15]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
roc_score

0.8654261704681873

In [16]:
print ( " the best parameter is ", grid.best_params_)

 the best parameter is  {'class_weight': None, 'criterion': 'entropy', 'max_features': None, 'splitter': 'best'}


In [17]:
grid.cv_results_

{'mean_fit_time': array([0.00657864, 0.00517993, 0.00658264, 0.00518355, 0.0057795 ,
        0.00698047, 0.00617657, 0.0035881 , 0.00438867, 0.00458755,
        0.00458851, 0.00479188, 0.00398989, 0.00418944, 0.00399027,
        0.00379176, 0.00398598, 0.00418921, 0.00100021, 0.00059819,
        0.00079846, 0.00079799, 0.00079856, 0.00039887, 0.00080366,
        0.00059876, 0.00039907, 0.00079799, 0.00079923, 0.0009995 ,
        0.00099778, 0.00079794, 0.00119915, 0.00099506, 0.00100088,
        0.00120015, 0.00418892, 0.00378928, 0.00299039, 0.00339212,
        0.0031919 , 0.00359025, 0.00378633, 0.00339174, 0.00378957,
        0.00418892, 0.00318666, 0.00359063, 0.00358791, 0.00319114,
        0.00439215, 0.00538979, 0.00438805, 0.00319147]),
 'std_fit_time': array([1.19833762e-03, 7.40357731e-04, 1.73939697e-03, 1.16971454e-03,
        9.75703734e-04, 2.81770263e-03, 7.45108215e-04, 4.87288909e-04,
        4.89220112e-04, 1.35237434e-03, 7.97879858e-04, 1.16386820e-03,
        4.623

In [18]:
re=grid.cv_results_

In [19]:
table= pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.006579  1.198338e-03         0.014960        0.003568   
1        0.005180  7.403577e-04         0.012567        0.001850   
2        0.006583  1.739397e-03         0.020150        0.004568   
3        0.005184  1.169715e-03         0.014756        0.001940   
4        0.005780  9.757037e-04         0.016759        0.003116   
5        0.006980  2.817703e-03         0.015163        0.001715   
6        0.006177  7.451082e-04         0.015359        0.002570   
7        0.003588  4.872889e-04         0.010970        0.000001   
8        0.004389  4.892201e-04         0.010572        0.001196   
9        0.004588  1.352374e-03         0.011768        0.003115   
10       0.004589  7.978799e-04         0.010970        0.001093   
11       0.004792  1.163868e-03         0.010966        0.000624   
12       0.003990  4.623108e-07         0.010173        0.000977   
13       0.004189  1.466311e-03         0.010771        0.000746   
14       0.003990  6.675720e-07         0.009580        0.000493   
15       0.003792  3.978986e-04         0.010175        0.001167   
16       0.003986  6.316095e-04         0.010971        0.001093   
17       0.004189  3.994945e-04         0.011968        0.001093   
18       0.001000  6.311554e-04         0.000000        0.000000   
19       0.000598  4.884224e-04         0.000000        0.000000   
20       0.000798  3.992326e-04         0.000000        0.000000   
21       0.000798  3.989941e-04         0.000000        0.000000   
22       0.000799  3.992804e-04         0.000000        0.000000   
23       0.000399  4.885197e-04         0.000000        0.000000   
24       0.000804  4.018904e-04         0.000000        0.000000   
25       0.000599  4.888904e-04         0.000000        0.000000   
26       0.000399  4.887529e-04         0.000000        0.000000   
27       0.000798  3.989951e-04         0.000000        0.000000   
28       0.000799  3.996161e-04         0.000000        0.000000   
29       0.000999  6.307007e-04         0.000000        0.000000   
30       0.000998  1.148376e-06         0.000000        0.000000   
31       0.000798  7.461494e-04         0.000000        0.000000   
32       0.001199  9.763953e-04         0.000000        0.000000   
33       0.000995  6.196315e-06         0.000000        0.000000   
34       0.001001  1.212236e-05         0.000000        0.000000   
35       0.001200  3.977447e-04         0.000000        0.000000   
36       0.004189  4.004720e-04         0.011370        0.001353   
37       0.003789  1.161413e-03         0.009571        0.000486   
38       0.002990  4.565202e-06         0.010971        0.001544   
39       0.003392  4.889870e-04         0.010172        0.000746   
40       0.003192  9.772431e-04         0.010573        0.001195   
41       0.003590  7.979395e-04         0.011170        0.000746   
42       0.003786  7.494325e-04         0.011570        0.002793   
43       0.003392  4.886174e-04         0.009973        0.000630   
44       0.003790  7.454355e-04         0.010777        0.001164   
45       0.004189  2.033690e-03         0.010374        0.000802   
46       0.003187  4.007780e-04         0.010976        0.000631   
47       0.003591  7.978324e-04         0.009978        0.000009   
48       0.003588  7.988626e-04         0.012367        0.002933   
49       0.003191  3.978496e-04         0.010373        0.001018   
50       0.004392  1.955069e-03         0.010567        0.000795   
51       0.005390  3.372687e-03         0.010768        0.001588   
52       0.004388  1.953722e-03         0.011570        0.001493   
53       0.003191  3.993516e-04         0.010973        0.001543   

   param_class_weight param_criterion param_max_features param_splitter  \
0            balanced            gini               None           best   
1            balanced            gini               None         random   
2            balanced            gini 

In [20]:
grid.best_score_

0.8801657906849198

In [21]:
pre_input= sc.transform([[35,60000,0]])
pre_input

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 6.90094695e+01,  5.91413422e+03, -2.05850391e+00]])

In [22]:
result= grid.predict(pre_input)
result

array([1], dtype=int64)