In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=dataset[["Gender_Male","Age",'EstimatedSalary']]
dep=dataset[["Purchased"]]

In [7]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid={'criterion':["gini", "entropy", "log_loss"], 'class_weight': ['balanced', 'dict', None], 'max_features': [None,"sqrt", "log2"], 'n_estimators':[10,50,100]}
grid= GridSearchCV(RandomForestClassifier(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted' )
grid.fit(X_train,y_train)

Fitting 5 folds for each of 81 candidates, totalling 405 fits


C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
135 fits failed out of a total of 405.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
135 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3run\Lib\site-packages\sklearn\utils\_param_validation.py", line 

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'dict', None],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             scoring='f1_weighted', verbose=3)

In [11]:
y_pred=grid.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[79,  6],
       [ 4, 45]], dtype=int64)

In [13]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [14]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        85
           1       0.88      0.92      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.92      0.92       134
weighted avg       0.93      0.93      0.93       134



In [15]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
roc_score

0.956062424969988

In [16]:
print ( " the best parameter is ", grid.best_params_)

 the best parameter is  {'class_weight': None, 'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}


In [17]:
grid.cv_results_

{'mean_fit_time': array([0.03949242, 0.14521165, 0.26788583, 0.03091569, 0.13144956,
        0.26089683, 0.03211522, 0.13324399, 0.258708  , 0.03730063,
        0.14501061, 0.29042344, 0.03809433, 0.1394249 , 0.25711107,
        0.03570161, 0.13084898, 0.2583075 , 0.03290715, 0.13763428,
        0.27705936, 0.03091607, 0.14002485, 0.26449547, 0.03311014,
        0.12805157, 0.28304462, 0.00039887, 0.00139408, 0.00159626,
        0.00119691, 0.0010076 , 0.00059252, 0.00059829, 0.00139542,
        0.0013958 , 0.00079641, 0.00119839, 0.00079789, 0.00039849,
        0.0011961 , 0.00119672, 0.00139313, 0.00099721, 0.00099483,
        0.00079761, 0.00099335, 0.00119619, 0.00119305, 0.00119658,
        0.00099835, 0.00119958, 0.00099478, 0.00059938, 0.03510299,
        0.13722539, 0.2650847 , 0.03351026, 0.13164802, 0.26369767,
        0.03270917, 0.13384061, 0.25172448, 0.0345046 , 0.14581046,
        0.27247119, 0.0299232 , 0.13244262, 0.26588898, 0.03131566,
        0.12885418, 0.26150813,

In [18]:
re=grid.cv_results_

In [19]:
table= pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.039492      0.004260         0.015159        0.002632   
1        0.145212      0.004213         0.019348        0.001353   
2        0.267886      0.005666         0.025131        0.001165   
3        0.030916      0.002523         0.013365        0.001197   
4        0.131450      0.006196         0.020145        0.002476   
..            ...           ...              ...             ...   
76       0.132246      0.006166         0.018949        0.001545   
77       0.255716      0.012027         0.026928        0.001784   
78       0.034709      0.005219         0.013562        0.001017   
79       0.137228      0.013576         0.018348        0.000490   
80       0.266481      0.020267         0.024135        0.000398   

   param_class_weight param_criterion param_max_features param_n_estimators  \
0            balanced            gini               None                 10   
1            balanced            gini               None                 50   
2            balanced            gini               None                100   
3            balanced            gini               sqrt                 10   
4            balanced            gini               sqrt                 50   
..                ...             ...                ...                ...   
76               None        log_loss               sqrt                 50   
77               None        log_loss               sqrt                100   
78               None        log_loss               log2                 10   
79               None        log_loss               log2                 50   
80               None        log_loss               log2                100   

                                               params  split0_test_score  \
0   {'class_weight': 'balanced', 'criterion': 'gin...           0.826263   
1   {'class_weight': 'balanced', 'criterion': 'gin...           0.847141   
2   {'class_weight': 'balanced', 'criterion': 'gin...           0.867478   
3   {'class_weight': 'balanced', 'criterion': 'gin...           0.804764   
4   {'class_weight': 'balanced', 'criterion': 'gin...           0.826263   
..                                                ...                ...   
76  {'class_weight': None, 'criterion': 'log_loss'...           0.867478   
77  {'class_weight': None, 'criterion': 'log_loss'...           0.826263   
78  {'class_weight': None, 'criterion': 'log_loss'...           0.804764   
79  {'class_weight': None, 'criterion': 'log_loss'...           0.847141   
80  {'class_weight': None, 'criterion': 'log_loss'...           0.847141   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.850809           0.851527           0.887907   
1            0.850809           0.851527           0.869709   
2            0.831253           0.833323           0.887907   
3            0.888107           0.851527           0.868632   
4            0.907177           0.851527           0.906166   
..                ...                ...                ...   
76           0.907177           0.851527           0.925272   
77           0.888107           0.851527           0.925272   
78           0.849057           0.850543           0.886792   
79           0.888107           0.851527           0.925272   
80           0.888107           0.851527           0.925272   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.883278         0.859957        0.022870               54  
1            0.924528         0.868743        0.028974               42  
2            0.924528         0.868898        0.035045               41  
3            0.922185         0.867043        0.039003               49  
4            0.962264         0.890679        0.047579               22  
..                ...              ...             ...              ...  
76           0.943699         0.899031        0.03

In [20]:
grid.best_score_

0.9027436637480886

In [21]:
pre_input= sc.transform([[35,60000,0]])
pre_input

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 6.90094695e+01,  5.91413422e+03, -2.05850391e+00]])

In [22]:
result= grid.predict(pre_input)
result

array([1], dtype=int64)

In [23]:
grid.n_splits_

5

In [24]:
grid.n_features_in_

3