In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=dataset[["Gender_Male","Age",'EstimatedSalary']]
dep=dataset[["Purchased"]]

In [7]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid={'kernel':['rbf','linear','sigmoid','poly'], 'C':[1,10,50,100], 'gamma':['auto','scale'], 'class_weight': ['balanced', 'dict', None], 'degree':[2]}
grid= GridSearchCV(SVC(probability=True), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'f1_weighted' )
grid.fit(X_train,y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits


C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
160 fits failed out of a total of 480.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
160 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3run\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3run\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3run\Lib\site-packages\sklearn\utils\_param_validation.py", line 

GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [1, 10, 50, 100],
                         'class_weight': ['balanced', 'dict', None],
                         'degree': [2], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear', 'sigmoid', 'poly']},
             scoring='f1_weighted', verbose=3)

In [11]:
y_pred=grid.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[78,  7],
       [ 5, 44]], dtype=int64)

In [13]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [14]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      0.92      0.93        85
           1       0.86      0.90      0.88        49

    accuracy                           0.91       134
   macro avg       0.90      0.91      0.90       134
weighted avg       0.91      0.91      0.91       134



In [15]:
from sklearn.metrics import roc_auc_score
roc_score= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
roc_score

0.9551020408163265

In [16]:
print ( " the best parameter is ", grid.best_params_)

 the best parameter is  {'C': 50, 'class_weight': 'balanced', 'degree': 2, 'gamma': 'auto', 'kernel': 'rbf'}


In [17]:
grid.cv_results_

{'mean_fit_time': array([0.01835189, 0.0153584 , 0.01396317, 0.01775179, 0.01635418,
        0.01575308, 0.01775141, 0.01635647, 0.00079751, 0.0010025 ,
        0.00080113, 0.00099745, 0.00059915, 0.00039907, 0.00099769,
        0.00059848, 0.01535673, 0.01296506, 0.01396012, 0.01695447,
        0.01356096, 0.01196752, 0.01356316, 0.01456089, 0.01455951,
        0.02134223, 0.01356421, 0.02453432, 0.0149611 , 0.01814799,
        0.01296492, 0.02094507, 0.00099778, 0.00079765, 0.00099988,
        0.00079908, 0.00079908, 0.00120049, 0.00099697, 0.00079751,
        0.01336384, 0.01595602, 0.01057119, 0.0177537 , 0.01416144,
        0.01695499, 0.0123672 , 0.01834998, 0.01994677, 0.03071637,
        0.01296473, 0.03251286, 0.0161562 , 0.03350983, 0.01276355,
        0.03650413, 0.00099735, 0.0003993 , 0.0005981 , 0.0011919 ,
        0.00059872, 0.0010004 , 0.00059719, 0.00099702, 0.01715336,
        0.03191476, 0.01097035, 0.03271194, 0.01735344, 0.02772593,
        0.01615686, 0.03330712,

In [18]:
re=grid.cv_results_

In [19]:
table= pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.018352      0.001018         0.013364        0.001353       1   
1        0.015358      0.002238         0.010771        0.001163       1   
2        0.013963      0.000631         0.012767        0.003178       1   
3        0.017752      0.002304         0.010369        0.001355       1   
4        0.016354      0.001492         0.012167        0.002394       1   
..            ...           ...              ...             ...     ...   
91       0.051263      0.008663         0.008976        0.000631     100   
92       0.018150      0.003240         0.010773        0.001163     100   
93       0.052259      0.011994         0.009776        0.001463     100   
94       0.013766      0.003485         0.009770        0.000745     100   
95       0.051261      0.009985         0.012368        0.006358     100   

   param_class_weight param_degree param_gamma param_kernel  \
0            balanced            2        auto          rbf   
1            balanced            2        auto       linear   
2            balanced            2        auto      sigmoid   
3            balanced            2        auto         poly   
4            balanced            2       scale          rbf   
..                ...          ...         ...          ...   
91               None            2        auto         poly   
92               None            2       scale          rbf   
93               None            2       scale       linear   
94               None            2       scale      sigmoid   
95               None            2       scale         poly   

                                               params  split0_test_score  \
0   {'C': 1, 'class_weight': 'balanced', 'degree':...           0.906808   
1   {'C': 1, 'class_weight': 'balanced', 'degree':...           0.777778   
2   {'C': 1, 'class_weight': 'balanced', 'degree':...           0.762677   
3   {'C': 1, 'class_weight': 'balanced', 'degree':...           0.670098   
4   {'C': 1, 'class_weight': 'balanced', 'degree':...           0.906808   
..                                                ...                ...   
91  {'C': 100, 'class_weight': None, 'degree': 2, ...           0.799620   
92  {'C': 100, 'class_weight': None, 'degree': 2, ...           0.867478   
93  {'C': 100, 'class_weight': None, 'degree': 2, ...           0.776290   
94  {'C': 100, 'class_weight': None, 'degree': 2, ...           0.808927   
95  {'C': 100, 'class_weight': None, 'degree': 2, ...           0.799620   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.889022           0.851527           0.944161   
1            0.834012           0.775815           0.796687   
2            0.668716           0.643430           0.778067   
3            0.718755           0.738451           0.787943   
4            0.889022           0.851527           0.944161   
..                ...                ...                ...   
91           0.804628           0.766556           0.783837   
92           0.886792           0.870362           0.944161   
93           0.790949           0.698235           0.923510   
94           0.714931           0.698113           0.796284   
95           0.804628           0.749387           0.783837   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.943699         0.907044        0.035009                7  
1            0.870362         0.810931        0.036332               31  
2            0.793565         0.729291        0.061100               49  
3            0.749387         0.732927        0.038669               46  
4            0.943699         0.907044        0.035009                7  
..                ...              ...             ...              ...  
91           0.783837         0.787696        0.013458               39  
92           0.943041         0.902367        0.034308               11 

In [20]:
grid.best_score_

0.918033132884488

In [21]:
pre_input= sc.transform([[35,60000,0]])
pre_input

C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 6.90094695e+01,  5.91413422e+03, -2.05850391e+00]])

In [22]:
result= grid.predict(pre_input)
result

array([1], dtype=int64)

In [28]:
age= int(input("age:"))
gender= int(input( "gender Male-1, Female-0 :"))
Salary= int(input("salary:"))
pre_input= sc.transform([[age,gender,Salary]])
pre_input
result= grid.predict(pre_input)
result

age:35
gender Male-1, Female-0 :5
salary:60000


C:\Anaconda3run\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1], dtype=int64)